package com.skysoft.nasa.utils

const val NASA_API_URL = "https://api.nasa.gov/"

const val KEY_CURRENT_SCREEN = "KEY_CURRENT_SCREEN"
const val KEY_CURRENT_THEME = "KEY_CURRENT_THEME"

const val SHARED_PREFERENCE_TAG = "SHARED_PREFERENCE_TAG"
const val FRAGMENT_APOD_TAG = "FRAGMENT_APOD_TAG"
const val FRAGMENT_EARTH_TAG = "FRAGMENT_EARTH_TAG"
const val FRAGMENT_MARS_TAG = "FRAGMENT_MARS_TAG"
const val FRAGMENT_SYSTEM_TAG = "FRAGMENT_SYSTEM_TAG"
const val FRAGMENT_SETTINGS_TAG = "FRAGMENT_SETTINGS_TAG"

const val THEME_LUNAR = 1
const val THEME_MARTIAN = 2
const val THEME_EARTH = 3
